version: '3.1'
services:
  app:
    container_name: postgres-springboot
    image: postgres-springboot
    build: ./
    ports:
      - "8888:8080"
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ecomerce
  